prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
 
grafana:
  adminPassword: "grafana0911"
  persistence:
    enabled: true
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.p-kh.ru
    tls:
      - hosts:
          - grafana.p-kh.ru
        secretName: grafana-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100