name: Reusable Checks

on:
  workflow_call:
    inputs:
      check-type:
        description: 'Type of check to run'
        type: string
        default: 'all'
        required: false
    secrets:
      KUBECONFIG:
        required: false

jobs:
  checks:
    uses: ./.github/workflows/typecheck.yml
